#!/usr/bin/env bash

set -e  # Exit on error

echo "Compiling Fennel plugin files to Lua..."

# Compile by opening each Fennel file and writing it (triggering nfnl's on-save hook)
cd res/plugins/grapple.nvim

# Use find to locate all .fnl files in grapple (excluding test directories)
find fnl/grapple -name "*.fnl" -type f | while read -r fnl_file; do
  echo "  Compiling $fnl_file..."
  nvim --headless -n \
    --cmd "set rtp+=." \
    -c "silent! edit $fnl_file" \
    -c "silent! write" \
    -c "qa"
done

cd ../../..

echo "Compilation complete!"
